// Emits paper/figs.tex (node test/gen_figs.js): TikZ pictures of the final spiral (both
// orientations out of the bottom-right corner), the eight corner
// snakes, and the last move.
"use strict";
var path = require("path");
var fs = require("fs");
var Super = require(path.join(__dirname, "..", "js", "super_ai.js"));
function rank(v) { return v ? Math.round(Math.log2(v)) : 0; }
// fill percentage by rank: 4 -> 8%, 131072 -> 100%
function pct(v) { var r = rank(v); return r ? Math.round(8 + (r - 2) * (92 / 15)) : 0; }
function boardTikz(vals, opts) {
  opts = opts || {};
  var scale = opts.scale || 1.0;
  var out = [];
  out.push("\\begin{tikzpicture}[x=" + (1.15 * scale) + "cm,y=" + (1.15 * scale) + "cm]");
  out.push("\\fill[boardbg,rounded corners=3pt] (-0.08,-0.08) rectangle (4.08,4.08);");
  for (var y = 0; y < 4; y++) for (var x = 0; x < 4; x++) {
    var v = vals[y * 4 + x];
    var X = x, Y = 3 - y;
    var p = pct(v);
    var fill = v ? "tile!" + p + "!tilelow" : "cellbg";
    var txt = v ? String(v) : "";
    var fs2 = v >= 100000 ? "\\tiny" : v >= 10000 ? "\\scriptsize" : v >= 1000 ? "\\footnotesize" : "\\small";
    var col = p > 45 ? "white" : "tiletext";
    out.push("\\fill[" + fill + ",rounded corners=2pt] (" + (X + 0.05) + "," + (Y + 0.05) + ") rectangle (" + (X + 0.95) + "," + (Y + 0.95) + ");");
    if (txt) out.push("\\node[" + col + ",font=" + fs2 + "\\bfseries] at (" + (X + 0.5) + "," + (Y + 0.5) + ") {" + txt + "};");
  }
  if (opts.path) {
    var pts = opts.path.map(function (c) { var x = c % 4, y = (c / 4) | 0; return "(" + (x + 0.5) + "," + (3 - y + 0.5) + ")"; });
    out.push("\\draw[pathline,-{Stealth[length=5pt]}] " + pts.join(" -- ") + ";");
  }
  if (opts.mark !== undefined) {
    var mx = opts.mark % 4, my = (opts.mark / 4) | 0;
    out.push("\\draw[markline,rounded corners=2pt] (" + (mx + 0.05) + "," + (3 - my + 0.05) + ") rectangle (" + (mx + 0.95) + "," + (3 - my + 0.95) + ");");
  }
  out.push("\\end{tikzpicture}");
  return out.join("\n");
}
function chainBoard(corner, orient) {
  var S = Super.snakeCells(corner, orient);
  var b = new Array(16).fill(0);
  for (var i = 0; i < 16; i++) b[S[i]] = 1 << (17 - i);
  return b;
}
var DIRWORD = { 0: "up", 1: "right", 2: "down", 3: "left" };
var CORNERWORD = { br: "bottom-right", bl: "bottom-left", tr: "top-right", tl: "top-left" };
function firstDir(corner, orient) {
  var S = Super.snakeCells(corner, orient);
  var a = S[0], b = S[1];
  var ax = a % 4, ay = (a / 4) | 0, bx = b % 4, by = (b / 4) | 0;
  if (bx > ax) return 1; if (bx < ax) return 3; if (by > ay) return 2; return 0;
}
var tex = [];
tex.push("% Generated by test/gen_figs.js from js/super_ai.js snakeCells — do not edit by hand.");
tex.push("\\newcommand{\\FigSpiralCol}{" + boardTikz(chainBoard("br", "col"), { scale: 1.15 }) + "}");
tex.push("\\newcommand{\\FigSpiralRow}{" + boardTikz(chainBoard("br", "row"), { scale: 1.15 }) + "}");
// eight snakes: empty boards with the path, corner marked
var snakes = [];
["tl", "tr", "bl", "br"].forEach(function (c) { ["row", "col"].forEach(function (o) {
  var S = Super.snakeCells(c, o);
  var b = new Array(16).fill(0);
  var pic = boardTikz(b, { scale: 0.42, path: S, mark: S[0] });
  var label = CORNERWORD[c] + ", " + DIRWORD[firstDir(c, o)];
  snakes.push("\\begin{minipage}[t]{0.23\\textwidth}\\centering\n" + pic + "\\\\[2pt]{\\footnotesize " + label + "}\\end{minipage}");
}); });
tex.push("\\newcommand{\\FigEightSnakes}{" + snakes.join("\\hfill\n") + "}");
// last move, col orientation: before (chain from 16 + two 4s), after slide, final
var S = Super.snakeCells("br", "col");
var before = chainBoard("br", "col");
before[S[14]] = 4; // the 8's cell holds a 4
before[S[15]] = 4;
var sim = Super.simMove(before, 0); // up
var afterSlide = sim.board.slice();
var fin = chainBoard("br", "col");
tex.push("\\newcommand{\\FigLastMoveA}{" + boardTikz(before, { scale: 0.62 }) + "}");
tex.push("\\newcommand{\\FigLastMoveB}{" + boardTikz(afterSlide, { scale: 0.62 }) + "}");
tex.push("\\newcommand{\\FigLastMoveC}{" + boardTikz(fin, { scale: 0.62, mark: S[15] }) + "}");
// primed board (tile line, move 32,766), col orientation
var primed = new Array(16).fill(0);
for (var i = 0; i < 15; i++) primed[S[i]] = 1 << (16 - i);
primed[S[15]] = 4;
tex.push("\\newcommand{\\FigPrimed}{" + boardTikz(primed, { scale: 0.62 }) + "}");
fs.writeFileSync(path.join(__dirname, "..", "paper", "figs.tex"), tex.join("\n") + "\n");
console.log("wrote paper/figs.tex; last-move slide merges " + JSON.stringify(sim.merges) + " moved=" + sim.moved);
console.log("after slide: " + afterSlide.join(","));
