#!/usr/bin/env python3
"""Generate kernel-checkable Lean chunks from witness/131072.txt.

The generator is deliberately *not* trusted: every emitted block is replayed
inside Lean by Game2048.Core and proved with `by decide`.  The Python code only
turns the human-readable certificate into Lean literals and convenient
checkpoints so the kernel never has to reduce all 32,781 moves in one term.
"""
from __future__ import annotations

import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "witness" / "131072.txt"
OUT = ROOT / "lean" / "Game2048" / "WitnessData.lean"
BLOCK = 256

DIR = {"U": "U", "R": "R", "D": "D", "L": "L"}
DNUM = {"U": 0, "R": 1, "D": 2, "L": 3}


def parse(path: pathlib.Path):
    starts = []
    steps = []
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        p = line.split()
        if p[0] == "start":
            if steps:
                raise SystemExit(f"{path}:{lineno}: start after moves")
            r, c, v = map(int, p[1:])
            starts.append((r, c, v))
        else:
            if p[0] not in DIR:
                raise SystemExit(f"{path}:{lineno}: bad direction")
            r, c, v = map(int, p[1:])
            steps.append((p[0], r, c, v))
    if len(starts) != 2:
        raise SystemExit("expected exactly two starting tiles")
    return starts, steps


def merge_line(vals):
    vals = [v for v in vals if v]
    out = []
    i = 0
    while i < len(vals):
        if i + 1 < len(vals) and vals[i] == vals[i + 1]:
            out.append(vals[i] * 2)
            i += 2
        else:
            out.append(vals[i])
            i += 1
    return out + [0] * (4 - len(out))


def slide(board, d):
    out = [0] * 16
    for i in range(4):
        if d in "UD":
            cells = [4 * r + i for r in range(4)]
        else:
            cells = [4 * i + c for c in range(4)]
        if d in "RD":
            cells.reverse()
        vals = merge_line([board[j] for j in cells])
        for j, v in zip(cells, vals):
            out[j] = v
    return out


def rank(v):
    if v == 0:
        return 0
    if v & (v - 1):
        raise SystemExit(f"non-power-of-two tile {v}")
    return v.bit_length() - 1


def board_lit(board):
    return "[" + ",".join(str(rank(v)) for v in board) + "]"


def step_lit(st):
    d, r, c, v = st
    return f"⟨.{DIR[d]}, {r}, {c}, {rank(v)}⟩"


def main():
    starts, steps = parse(SRC)
    if starts != [(3, 2, 4), (3, 3, 4)]:
        raise SystemExit(f"unexpected canonical start: {starts}")
    if len(steps) != 32781:
        raise SystemExit(f"expected 32781 moves, got {len(steps)}")

    board = [0] * 16
    for r, c, v in starts:
        if not (0 <= r < 4 and 0 <= c < 4 and v in (2, 4)) or board[4*r+c]:
            raise SystemExit("bad start")
        board[4*r+c] = v

    chunks = []
    checkpoints = [board[:]]
    for base in range(0, len(steps), BLOCK):
        chunk = steps[base:base + BLOCK]
        for off, (d, r, c, v) in enumerate(chunk):
            moved = slide(board, d)
            if moved == board:
                raise SystemExit(f"illegal move at {base + off + 1}")
            if v not in (2, 4) or not (0 <= r < 4 and 0 <= c < 4):
                raise SystemExit(f"bad spawn at {base + off + 1}")
            j = 4*r+c
            if moved[j]:
                raise SystemExit(f"occupied spawn at {base + off + 1}")
            moved[j] = v
            board = moved
        chunks.append(chunk)
        checkpoints.append(board[:])

    if max(board) != 131072:
        raise SystemExit("certificate does not end with 131072")

    sha = hashlib.sha256(SRC.read_bytes()).hexdigest()
    lines = [
        "-- AUTO-GENERATED by lean/gen_witness.py from witness/131072.txt.",
        "-- The generator is not trusted: each block theorem below is checked by Lean.",
        f"-- SHA-256: {sha}",
        "import Game2048.Core",
        "",
        "namespace Game2048.WitnessData",
        "",
        f'def sourceSha256 : String := "{sha}"',
        "",
    ]

    for i, cp in enumerate(checkpoints):
        lines.append(f"def cp{i} : Board := {board_lit(cp)}")
    lines.append("")

    for i, chunk in enumerate(chunks):
        body = ",\n    ".join(step_lit(s) for s in chunk)
        lines += [
            f"def block{i} : List Step := [",
            f"    {body}",
            "]",
            f"theorem block{i}_length : block{i}.length = {len(chunk)} := by rfl",
            f"set_option maxRecDepth 100000 in",
            f"theorem block{i}_valid : replay cp{i} block{i} = some cp{i+1} := by decide",
            "",
        ]

    block_names = [f"block{i}" for i in range(len(chunks))]
    lines.append("def witnessSteps : List Step :=")
    # Right-associated append lets replay_append consume one certified block at a time.
    expr = block_names[-1]
    for name in reversed(block_names[:-1]):
        expr = f"{name} ++ ({expr})"
    lines.append(f"  {expr}")
    lines.append("")

    len_thms = ", ".join(f"block{i}_length" for i in range(len(chunks)))
    lines += [
        "theorem witness_length : witnessSteps.length = 32781 := by",
        f"  simp only [witnessSteps, List.length_append, {len_thms}]",
        "",
        "theorem witness_replay : replay witnessStart witnessSteps = some cp" + str(len(chunks)) + " := by",
        "  change replay cp0 witnessSteps = some cp" + str(len(chunks)),
        "  simp only [witnessSteps, replay_append, " + ", ".join(f"block{i}_valid" for i in range(len(chunks))) + "]",
        "",
        "theorem witness_has_131072 : containsRank cp" + str(len(chunks)) + " 17 = true := by decide",
        "",
        "end Game2048.WitnessData",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"generated {OUT.relative_to(ROOT)}: {len(steps)} moves, {len(chunks)} blocks, sha256={sha}")


if __name__ == "__main__":
    main()
