#!/usr/bin/env node
"use strict";
// Separate BigInt count of the geometry + causal-supply superset.
// No tables or data generated by the Python implementation are imported.
const choose = (n,k) => {let z=1n;for(let j=1;j<=k;j++)z=z*BigInt(n-j+1)/BigInt(j);return z;};
const pop=x=>{let n=0;while(x){x&=x-1;n++;}return n;};
const fns=[(r,c)=>[r,c],(r,c)=>[c,3-r],(r,c)=>[3-r,3-c],(r,c)=>[3-c,r],(r,c)=>[r,3-c],(r,c)=>[3-r,c],(r,c)=>[c,r],(r,c)=>[3-c,3-r]];
const perms=fns.map(f=>Array.from({length:16},(_,i)=>{const [r,c]=f(i>>2,i%4);return r*4+c;}));
function cycles(p){const seen=new Set(),cs=[];for(let i=0;i<16;i++)if(!seen.has(i)){let j=i,cy=[];while(!seen.has(j)){seen.add(j);cy.push(j);j=p[j];}cs.push(cy);}return cs;}
const eligibility=new Int32Array(65536).fill(-1);
function compact(m,transpose,reverse){
 for(let i=0;i<4;i++){
  let word="";for(let j=0;j<4;j++){const k=reverse?3-j:j;word+=((m>>(transpose?4*k+i:4*i+k))&1);}
  if(!/^1*0*$/.test(word))return false;
 }return true;
}
function eligible(m){
 if(eligibility[m]>=0)return eligibility[m];let e=0;
 for(let x=0;x<16;x++)if(m&(1<<x)){
  const a=m^(1<<x);
  if(compact(a,false,false)||compact(a,false,true)||compact(a,true,false)||compact(a,true,true))e|=1<<x;
 }eligibility[m]=e;return e;
}
const highMemo=new Map();
function high(counts,q,units,fours){
 const k=[...counts,q,units,fours].join(",");if(highMemo.has(k))return highMemo.get(k);
 const n=counts[0]+2*counts[1]+4*counts[2];
 if(!n)return 1n;
 if(q>17||n>18-q)return 0n;
 const force=units<=q-2+fours;let ans=0n;
 for(let a=0;a<=counts[0];a++)for(let b=0;b<=counts[1];b++)for(let c=0;c<=counts[2];c++){
  const used=a+2*b+4*c;if(force&&!used)continue;
  const mult=choose(counts[0],a)*choose(counts[1],b)*choose(counts[2],c);
  ans+=mult*high([counts[0]-a,counts[1]-b,counts[2]-c],q+1,Math.min(32,units+(2**(q-1))*used),fours+(force?1:0));
 }highMemo.set(k,ans);return ans;
}
const assignmentMemo=new Map();
function assignments(types){
 const key=types.map(t=>t.join(":")).join("|");if(assignmentMemo.has(key))return assignmentMemo.get(key);
 // Enumerate low-color counts directly rather than using Python's low-rank DP.
 let ans=0n;
 function recur(i,remaining,units,e2,e4,mult){
  if(i===types.length){if(e2||e4)ans+=mult*high(remaining,3,Math.min(32,units),e2?0:1);return;}
  const [length,flag,num]=types[i],index={1:0,2:1,4:2}[length];
  for(let twos=0;twos<=num;twos++)for(let fours=0;fours<=num-twos;fours++){
   const rem=remaining.slice();rem[index]+=num-twos-fours;
   recur(i+1,rem,units+length*(twos+2*fours),e2||(flag&&twos>0),e4||(flag&&fours>0),mult*choose(num,twos)*choose(num-twos,fours));
  }
 }
 recur(0,[0,0,0],0,false,false,1n);assignmentMemo.set(key,ans);return ans;
}
const fixed=[];
for(const p of perms){
 const cs=cycles(p),hist=new Map();
 for(let sel=0;sel<(1<<cs.length);sel++){
  let mask=0,occ=[];
  cs.forEach((cy,j)=>{if(sel&(1<<j)){occ.push(cy);for(const x of cy)mask|=1<<x;}});
  if(pop(mask)<2)continue;
  const e=eligible(mask);if(!e)continue;
  const groups=new Map();
  for(const cy of occ){const flags=cy.map(x=>!!(e&(1<<x)));if(flags.some(Boolean)&&!flags.every(Boolean))throw Error("invariant eligible set");const k=[cy.length,flags[0]?1:0].join(":");groups.set(k,(groups.get(k)||0)+1);}
  const types=[...groups].map(([k,n])=>[...k.split(":").map(Number),n]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);
  const k=JSON.stringify(types);hist.set(k,(hist.get(k)||0)+1);
 }
 let total=0n;for(const [k,n] of hist)total+=BigInt(n)*assignments(JSON.parse(k));fixed.push(total);
}
const extras=[];
for(let i=0;i<16;i++)for(let j=i+1;j<16;j++)if(!eligible((1<<i)|(1<<j)))for(const a of [2,4])for(const b of [2,4]){const x=Array(16).fill(0);x[i]=a;x[j]=b;extras.push(x);}
const ef=perms.map(p=>BigInt(extras.filter(b=>b.every((v,i)=>v===b[p[i]])).length));
const sum=a=>a.reduce((x,y)=>x+y,0n);
if(sum(fixed)%8n||sum(ef)%8n)throw Error("Burnside divisibility");
const result={fixed:fixed.map(String),initial_fixed:ef.map(String),labeled:String(fixed[0]+ef[0]),orbits:String((sum(fixed)+sum(ef))/8n)};
if(result.labeled!=="22851583961907351152"||result.orbits!=="2856448098561271997")throw Error("regression mismatch");
console.log(JSON.stringify(result,null,2));
